import Head from 'next/head'
import Image from 'next/image'

import Hero from '../components/Hero'
import Slider from '../components/Slider'
import Instagram from '../components/Instagram'

import { SliderData } from '../components/SlidaerData'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Rhaqim's Photography" message="I take pictures of the best Resaturants in Lagos"/>
      <Slider data={SliderData}/>
      <Instagram />
    </div>
  )
}
